apiVersion: v1
kind: Namespace
metadata:
  name: nats
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: nats
data:
  NATS_URL: "nats://nats.nats.svc.cluster.local:4222"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: nats
spec:
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
