import os

POD_NAME = os.getenv("POD_NAME")
POD_NAMESPACE = os.getenv("POD_NAMESPACE")
CONTAINER_NAME = os.getenv("CONTAINER_NAME")
HOST_POD_METRICS_MOUNT_PATH = os.getenv("HOST_POD_METRICS_MOUNT_PATH")

MONITORING_INTERVAL = int(os.getenv("MONITORING_INTERVAL"))
CPU_OBSERVATION_INTERVAL = int(os.getenv("CPU_OBSERVATION_INTERVAL"))

MONITORING_TOPIC = os.getenv("MONITORING_TOPIC")
