import os

CPU_USAGE_THRESHOLD = int(os.getenv("CPU_USAGE_THRESHOLD"))
RAM_USAGE_THRESHOLD = int(os.getenv("RAM_USAGE_THRESHOLD"))
MONITORING_INTERVAL = os.getenv("MONITORING_INTERVAL")
CPU_OBSERVATION_INTERVAL = os.getenv("CPU_OBSERVATION_INTERVAL")

RCN_NAME = os.getenv("RCN_NAME")

RESTORE_POLICY = os.getenv("RESTORE_POLICY")

POD_NAME = os.getenv("POD_NAME")
POD_NAMESPACE = os.getenv("POD_NAMESPACE")
CONTAINER_NAME = os.getenv("CONTAINER_NAME")
CHECKPOINTS_DIR_PATH = os.getenv("CHECKPOINTS_DIR_PATH")
