apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-controller
  namespace: criu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: criu
  name: pod-controller
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-controller
  namespace: criu
subjects:
  - kind: ServiceAccount
    name: pod-controller
    namespace: criu
roleRef:
  kind: Role
  name: pod-controller
  apiGroup: rbac.authorization.k8s.io
