apiVersion: v1
kind: ServiceAccount
metadata:
  name: test 
  namespace: criu
---
apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRole
metadata:
  name: criu-test 
rules:
  - apiGroups: ["criu.thesis"]
    resources: ["edgenodes"]
    verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: criu-test 
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: criu-test 
subjects:
  - kind: ServiceAccount
    name: test
    namespace: criu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test
  namespace: criu
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test
  namespace: criu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test
subjects:
  - kind: ServiceAccount
    name: test
    namespace: criu
