import os

CPU_USAGE_THRESHOLD = os.getenv("CPU_USAGE_THRESHOLD")
RAM_USAGE_THRESHOLD = os.getenv("RAM_USAGE_THRESHOLD")
MONITORING_INTERVAL = os.getenv("MONITORING_INTERVAL")
CPU_OBSERVATION_INTERVAL = os.getenv("CPU_OBSERVATION_INTERVAL")

RESTORE_POLICY = os.getenv("RESTORE_POLICY")

RCN_NAME = os.getenv("RCN_NAME")

NAMESPACE = os.getenv("SETUP_NAMESPACE")
