from tests.config import EDGE_NODE_GROUP

CPU_USAGE_THRESHOLD = 90
RAM_USAGE_THRESHOLD = 90
MONITORING_INTERVAL = 1
CPU_OBSERVATION_INTERVAL = 1
RESTORE_POLICY = "restart"

APP_POD_NAME = "image-reduction"
APP_POD_LAYER = "edge"
APPLICATION_IMAGE = "nefks/image-reduction:latest"

POD_CONTROLLER_DEPLOYMENT_NAME = f"{EDGE_NODE_GROUP}-pod-controller"
SIDECAR_CONTROLLER_JOB_NAME = f"{EDGE_NODE_GROUP}-sidecar-controller-{APP_POD_NAME}"
